apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-wasmedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-wasmedge
  template:
    metadata:
      labels:
        app: rust-wasmedge
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      runtimeClassName: wasmedge-crun
      containers:
        - name: rust-wasmedge
          image: ghcr.io/huangyingting/rust-wasmedge:main
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rust-wasmedge
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: rust-wasmedge
