specversion = "0.2"

[[capability]]
resource = "http"
name = "rust-slight"

[[capability]]
resource = "kv.redis"
name = "rust-slight"
    [capability.configs]
    REDIS_ADDRESS = "${envvars.REDIS_ADDRESS}"
